  on: ["push","pull_request"]

  name: Test

  jobs:

    build:
      name: Build
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: make test
        run: |
          make build-builder test BUILDER_IMAGE=kubevirt-velero-plugin-builder
